## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [59]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [2]:
# code here
pclass = titanic_df.groupby("Pclass")
pclass['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [3]:
pclass['Age'].apply(lambda x : x.isnull().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [20]:
# code here
titanic_df['Embarked'] = pclass['Embarked'].transform( lambda x : x.fillna(x.mode()[0]))
for group , data in pclass: 
    print(f"\nPclass {group} Embarked Value Counts:")
    print(data['Embarked'].value_counts(ascending=True))

Pclass 1 Embarked Value Counts:
Embarked
Q      2
C     85
S    129
Name: count, dtype: int64

Pclass 2 Embarked Value Counts:
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64

Pclass 3 Embarked Value Counts:
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [31]:
# code here
for data , group in titanic_df.groupby('Embarked'): 
    fare = group.groupby('Pclass')['Fare'].mean().round(2)
    print(f'\nAverage fare for {data} Embarked')
    print(fare)

Average fare for C Embarked
Pclass
1    104.72
2     25.36
3     11.21
Name: Fare, dtype: float64

Average fare for Q Embarked
Pclass
1    90.00
2    12.35
3    11.18
Name: Fare, dtype: float64

Average fare for S Embarked
Pclass
1    70.51
2    20.33
3    14.64
Name: Fare, dtype: float64

In [32]:
result = {}
for embarked , group in titanic_df.groupby('Embarked'): 
    fare = group.groupby('Pclass')['Fare'].mean().round(2)
    result[embarked] = fare.to_dict()

print(result)

{'C': {1: 104.72, 2: 25.36, 3: 11.21}, 'Q': {1: 90.0, 2: 12.35, 3: 11.18}, 'S': {1: 70.51, 2: 20.33, 3: 14.64}}

In [22]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [41]:
fifa_df

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

In [47]:
def z_normalization(group , col_to_perform): 
    group = group.copy()
    for col in col_to_perform:
        group[col] = (group[col] - group[col].mean())/ group[col].std()

    return group

cols = [
    'Passes',
    'Passes Completed',
    'Attempted Line Breaks',
    'Completed Line Breaks'
]

In [58]:
# code here
fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
fifa_df.shape

normalized_df = fifa_df.groupby('Team').apply( lambda x : z_normalization(x , cols),include_groups=False)

result = fifa_df.groupby('Team').agg({
                                    'Passes': ['min','max'],
                                   'Yellow Cards': ['min','max','mean'],
                                   "Attempted Line Breaks": ['min','max','mean','std'],
                                   'Possession (%)': 'mean'
                                  })
result

               Passes       Yellow Cards               Attempted Line Breaks  \
                  min   max          min max      mean                   min
Team
Argentina         408   862            0   8  2.285714                   141
Australia         286   466            0   3  1.750000                   133
Belgium           512   685            1   3  1.666667                   167
Brazil            548   695            0   3  1.200000                   164
Cameroon          295   500            1   5  2.666667                   144
Canada            448   536            2   4  2.666667                   102
Costa Rica        231   454            1   3  2.000000                    86
Croatia           461   724            0   2  1.142857                    97
Denmark           537   650            1   2  1.666667                   173
Ecuador           429   484            0   2  1.000000                   143
England           508   810            0   1  0.200000                   133
France            358   734            0   3  1.142857                   126
Germany           352   827            0   3  1.000000                   143
Ghana             319   460            2   4  2.666667                   122
Iran              232   463            2   3  2.333333                    56
Japan             225   591            0   3  1.500000                   104
Korea Republic    359   548            1   2  1.500000                   139
Mexico            356   500            1   4  2.333333                   127
Morocco           229   583            0   3  1.285714                   128
Netherlands       403   786            0   4  1.800000                   168
Poland            303   466            1   3  1.750000                    79
Portugal          461   678            0   3  1.200000                   165
Qatar             424   457            0   4  2.333333                   159
Saudi Arabia      267   560            2   6  4.666667                   147
Senegal           277   511            1   3  1.750000                   143
Serbia            403   513            2   7  4.000000                   140
Spain             647  1070            0   1  0.500000                   186
Switzerland       403   512            1   4  2.250000                   157
Tunisia           328   501            1   3  1.666667                   153
United States     427   572            0   4  1.250000                   143
Uruguay           390   528            1   3  2.000000                   146
Wales             325   508            1   2  1.666667                   104

                                           Possession (%)
                max        mean        std           mean
Team
Argentina       249  180.857143  38.774685      49.285714
Australia       171  154.000000  17.682383      31.250000
Belgium         195  179.000000  14.422205      49.000000
Brazil          193  181.400000  10.691118      50.400000
Cameroon        182  166.333333  19.857828      38.333333
Canada          176  143.333333  37.753587      44.333333
Costa Rica      154  131.000000  38.974351      27.333333
Croatia         259  194.285714  54.499891      47.428571
Denmark         241  207.000000  34.000000      51.333333
Ecuador         177  159.666667  17.009801      42.666667
England         208  167.800000  29.676590      57.200000
France          179  154.428571  21.407609      44.857143
Germany         256  197.333333  56.624494      53.000000
Ghana           188  155.666667  33.020196      37.000000
Iran            195  145.333333  77.526340      31.666667
Japan           253  164.750000  64.048810      30.250000
Korea Republic  201  178.250000  27.072434      42.250000
Mexico          198  174.000000  40.706265      46.666667
Morocco         157  146.285714  10.641339      34.285714
Netherlands     198  183.600000  12.759310      44.000000
Poland          156  133.250000  36.326070      32.000000
Portugal        197  175.400000  13.049904      53.800000
Qatar           174  165.333333   7.767453      39.333333
Saudi Arabia    205  176.666667  29.022979      36.666667
Senegal         184  161.250000  16.938615      38.500000
Serbia          184  160.333333  22.188586      42.666667
Spain           237  208.000000  24.289916      67.000000
Switzerland     178  168.750000   9.032349      43.000000
Tunisia         200  180.333333  24.419937      38.666667
United States   204  182.750000  27.693260      47.000000
Uruguay         186  160.666667  22.030282      41.000000
Wales           208  162.000000  53.028294      41.000000

In [56]:
f =  fifa_df.groupby('Team') 
f.get_group('Qatar')

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
34,35,18,Qatar,Senegal,A,1,42,1,0,1,...,7,4,424,353,18,5,6,15,0,0
65,66,33,Qatar,Netherlands,A,0,36,0,0,0,...,0,0,457,394,18,4,2,24,0,0

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

###`Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [ ]:
# code here

###`Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [ ]:
# code here

###`Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [ ]:
# code here

###`Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [ ]:
# code here